version: '3'

services:
  database:
    container_name: mysql-vollmed
    image: mysql:oraclelinux8
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=vollmed_api
    volumes:
      - /volumes/mysql:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api-service:
    container_name: spring-vollmed-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://database/vollmed_api
      - DATASOURCE_USER=root
      - DATASOURCE_PASSWORD=1234
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy